
services:
  redis:
    image: redis:8.2.2
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CLUSTER_ID: "Lel53Ee8RvGx4n0cQJ6q9A"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # -----------------------------------------------------------------------------------------
  api:
    build: .
    container_name: sec_kill_proj
    depends_on:
      - redis
      - kafka
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: ["uv", "run", "startup.py"]
    environment:
      REDIS_HOST: redis
      KAFKA_HOST: kafka:29092
      PYTHONUNBUFFERED: 1

  consumer:
    build: .
    container_name: consumer
    depends_on:
      - kafka
    volumes:
      - ./app:/app/app
    command: ["python", "-u", "app/consumer/order_consumer.py"]
    environment:
      KAFKA_HOST: kafka:29092
      PYTHONUNBUFFERED: 1
